### ISSUE TITLE
Wrong behavior when "url()" contains ")"

### ISSUE THREAD

**Issue by kapokyue** [thysultan/stylis.js#123] opened 2018-10-05 04:12 UTC
I originally found this issue when I tried to use styled-jsx to write something like

```css
.a {
    background: url("rotate)");
}

.b {
    background: url("abc");
}
```

and error happened.

I opened an issue: zeit/styled-jsx#500.

@giuseppeg reported that this is a bug in Stylis.

I also tried to write the same code in https://stylis.js.org/, and the result is

```css
.scope .a {
	background: url("rotate)");
}

.scope .a .b {
	background: url("abc");
}
```

**Comment by jaydenseric** [comment] 2019-01-07 04:07
Oof, this is a showstopper when attempting to load the Mapbox CSS:

- https://github.com/zeit/styled-jsx#styles-in-regular-css-files
- https://uber.github.io/react-map-gl/#/Documentation/getting-started/get-started?section=styling
- https://unpkg.com/mapbox-gl@0.52.0/dist/mapbox-gl.css

<img width="353" alt="screen shot 2019-01-07 at 3 00 59 pm" src="https://user-images.githubusercontent.com/1754873/50748333-172ca000-128d-11e9-9f06-a447a09f8f46.png">

**Comment by Soundvessel** [comment] 2019-03-29 16:23
@thysultan I have another workflow related to this that breaks down because of this bug

Error and initial comment.
https://github.com/zeit/styled-jsx/issues/557#issuecomment-477788258

Codesandboxes confirming the issue isn't external SASS path. You should be able to clone the second one and uncomment the bootstrap import to use as a test for a fix.
https://github.com/zeit/styled-jsx/issues/557#issuecomment-477800041

**Comment by bensaufley** [comment] 2019-06-13 23:31
This is not a full solution but I knew exactly where I had a data-url with a parenthesis and so I was able to do the below to the offending string and … it seems to have solved my problem. Figured I'd post it here.

```js
.replace(/\(/g, '\\u0028').replace(/\)/g, '\\u0029')
```

**Comment by Soundvessel** [comment] 2019-06-19 21:59
@thysultan I don't see any activity on this project for the last 3 months. Should the community look at trying to find someone new to take over the repo and/or crowdsource a bounty to get a fix in place?

**Comment by Andarist** [comment] 2020-01-10 22:40
This got fixed in the upcoming v4:
https://github.com/thysultan/stylis.js/blob/5cb4a8a7541ba224d77825900790bb38768362d6/test/index.js#L774-L789

**Closed by Andarist** 2020-01-10 22:40 UTC
Labels: bug

**Comment by nodabladam** [comment] 2020-02-28 18:00
Any chance there is a version of v4 available that could be used?

**Comment by Andarist** [comment] 2020-02-28 18:33
Its still in the works.
