### ISSUE TITLE
CSS Grid Autoprefixing Support

### ISSUE THREAD

**Issue by collegeimprovements** [thysultan/stylis.js#145] opened 2019-05-15 05:55 UTC
Hi Team,

There is an [issue](https://github.com/thysultan/stylis.js/issues/119) related to auto-prefixing for `css-grid`.
What is the current workaround currently? 
Should we refrain from writing any css-grid ?
Or `Stylis` is going to support css-grid at some point of time in future ?

**Comment by pjaws** [comment] 2020-01-30 23:53
@collegeimprovements Use PostCSS/Autoprefixer instead, I guess.

**Comment by Andarist** [comment] 2020-03-09 08:38
Duplicate of #119

**Closed by Andarist** 2020-03-09 08:38 UTC
