### ISSUE TITLE
Nested at-rule

### ISSUE THREAD

**Issue by geelen** [thysultan/stylis.js#59] opened 2017-09-06 08:15 UTC
Was working on some styled-components stuff, and I think I've found a bug.

Here's the code I'm running (just to get a sense of how the plugins work atm) using `v3.2.8`:

```js
import Stylis from 'stylis'

const stylis = new Stylis({
  global: false,
  cascade: true,
  keyframe: false,
  prefix: true,
  compress: false,
  semicolon: true,
})

const plugin_calls = []
stylis.use((context, content, selectors, parent, line, column, length) => {
  plugin_calls.push({ context, content, selectors, parent, line, column, length })
})
stylis('.foo', `
  bar: baz;
  @media screen and (min-width: 600px) { 
    yeah: nah;
    @supports (lol) {
      too: right;
    }
  }
`)
console.log(JSON.stringify(plugin_calls, null, 2))
```

```json
[
  {
    "context": -1,
    "content": "\n  bar: baz;\n  @media screen and (min-width: 600px) { \n    yeah: nah;\n    @supports (lol) {\n      too: right;\n    }\n  }\n",
    "selectors": [
      ".foo"
    ],
    "parent": [
      ".foo"
    ],
    "line": 1,
    "column": 1,
    "length": 0
  },
  {
    "context": 1,
    "content": "bar:baz",
    "selectors": [
      ".foo"
    ],
    "parent": [],
    "line": 2,
    "column": 11,
    "length": 0
  },
  {
    "context": 1,
    "content": "yeah:nah",
    "selectors": [
      ".foo"
    ],
    "parent": [
      ".foo"
    ],
    "line": 4,
    "column": 14,
    "length": 0
  },
  {
    "context": 1,
    "content": "too:right",
    "selectors": [
      ".foo"
    ],
    "parent": [
      ".foo"
    ],
    "line": 6,
    "column": 17,
    "length": 0
  },
  {
    "context": 2,
    "content": "too:right;",
    "selectors": [
      ".foo"
    ],
    "parent": [
      ".foo"
    ],
    "line": 7,
    "column": 5,
    "length": 10
  },
  {
    "context": 3,
    "content": ".foo{too:right;}",
    "selectors": [
      "@supports (lol)"
    ],
    "parent": [
      ".foo"
    ],
    "line": 7,
    "column": 5,
    "length": 16
  },
  {
    "context": 2,
    "content": "yeah:nah;",
    "selectors": [
      ".foo"
    ],
    "parent": [
      ".foo"
    ],
    "line": 8,
    "column": 3,
    "length": 9
  },
  {
    "context": 3,
    "content": ".foo{yeah:nah;}@supports (lol){.foo{too:right;}}",
    "selectors": [
      "@media screen and (min-width:600px)"
    ],
    "parent": [
      ".foo"
    ],
    "line": 8,
    "column": 3,
    "length": 48
  },
  {
    "context": 2,
    "content": "bar:baz;",
    "selectors": [
      ".foo"
    ],
    "parent": [],
    "line": 9,
    "column": 1,
    "length": 8
  },
  {
    "context": -2,
    "content": ".foo{bar:baz;}@media screen and (min-width:600px){.foo{yeah:nah;}@supports (lol){.foo{too:right;}}}",
    "selectors": [
      ".foo"
    ],
    "parent": [
      ".foo"
    ],
    "line": 9,
    "column": 1,
    "length": 99
  }
]
```

To my mind, the first `"context": 3,` callback (for `"content": ".foo{too:right;}",`) should have a parent of `[".foo", "@media screen and (min-width:600px)"]`, not just `.foo`. I'm guessing somewhere there's an expectation that at-rules can only be one level deep, which isn't the case (`@media` and `@supports` work just fine nested, at least).

I'm trying to build a simple plugin that can do the sort of thing described here: https://github.com/threepointone/glam/issues/5 to make stylis' output `insertRule`-able.

Would there be a better way to approach this?

**Comment by thysultan** [comment] 2017-09-06 09:16
Created this plugin that generates an AST [https://github.com/thysultan/stylis.js/blob/master/plugins/ast/](https://github.com/thysultan/stylis.js/blob/master/plugins/ast/index.js), maybe that can also help.

Can't remember the reason i implemented it like that and if that was intended or not but will look into it.

**Comment by thysultan** [comment] 2017-10-06 23:32
I think the reason it's like that is because nested @media queries aren't represented as ancestors in the sense of a selector relationship i.e `#a > #b` of the nesting they appear in. This only reflects on selectors blocks that can be concat-ed to make a valid selector.

```css
#a { #b {} } -> #a #b {}

#a { @media { #b } } -> @media { #a #b {} }
```
Though i'm open to improving this heuristic.

**Comment by k15a** [comment] 2017-11-13 13:05
This is also a problem for a nested @-rule in `@page` which is needed for [CSS Generated Content for Paged Media Module](https://www.w3.org/TR/css-gcpm-3/)

Input:
```css
@page {
    @bottom-right {
        content: 'Page ' counter(page) ' of ' counter(pages);
        margin-right: 1cm;
    }
}
```

Output:
```css
@page@bottom-right {
	content: 'Page ' counter(page) ' of ' counter(pages);
	margin-right: 1cm;
}
```

Expected output is the same as the input.

**Comment by thysultan** [comment] 2017-11-13 13:11
@k15a Though unrelated the fix for that looks identical to the fix for #71 – will publish a patch for that.

**Comment by thysultan** [comment] 2017-11-13 16:13
@k15a 3.4.2 patches the nested `@page` issue.

**Comment by giuseppeg** [comment] 2018-02-16 08:46
@thysultan this is fixed now right?

**Closed** 2018-06-19 08:14 UTC
